apiVersion: v1
kind: Service
metadata:
  name: shop-app-service
  namespace: python-shop
spec:
  type: ClusterIP
  selector:
    name: shop-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000