apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: python-shop
spec:
  type: ClusterIP
  selector:
    name: payment-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
